apiVersion: apps/v1
kind: Deployment
metadata:
  name: ip-headless
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ip-app
  template:
    metadata:
      labels:
        app: ip-app
    spec:
      containers:
        - name: ip-container
          image: harshajain/ip_app:2
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cluster-ip
spec:
  type: ClusterIP
  selector:
    app: ip-app
  ports:
    - name: http
      port: 30005
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nodeport
spec:
  type: NodePort
  selector:
    app: ip-app
  ports:
    - name: http
      port: 30005
      targetPort: 8080
      nodePort: 30006
